Homework 3
================
Xuange Liang (xl3493)
2025-10-13

## Problem 1: Instacart Data Analysis

This problem explores the Instacart online grocery shopping dataset to
understand purchasing patterns and popular products.

### Loading required libraries and data

``` r
library(tidyverse)
library(p8105.datasets)

data("instacart")
```

### Dataset Description

``` r
# Explore dataset structure
str(instacart) # Structure of the dataset
```

    ## tibble [1,384,617 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ order_id              : int [1:1384617] 1 1 1 1 1 1 1 1 36 36 ...
    ##  $ product_id            : int [1:1384617] 49302 11109 10246 49683 43633 13176 47209 22035 39612 19660 ...
    ##  $ add_to_cart_order     : int [1:1384617] 1 2 3 4 5 6 7 8 1 2 ...
    ##  $ reordered             : int [1:1384617] 1 1 0 0 1 0 0 1 0 1 ...
    ##  $ user_id               : int [1:1384617] 112108 112108 112108 112108 112108 112108 112108 112108 79431 79431 ...
    ##  $ eval_set              : chr [1:1384617] "train" "train" "train" "train" ...
    ##  $ order_number          : int [1:1384617] 4 4 4 4 4 4 4 4 23 23 ...
    ##  $ order_dow             : int [1:1384617] 4 4 4 4 4 4 4 4 6 6 ...
    ##  $ order_hour_of_day     : int [1:1384617] 10 10 10 10 10 10 10 10 18 18 ...
    ##  $ days_since_prior_order: int [1:1384617] 9 9 9 9 9 9 9 9 30 30 ...
    ##  $ product_name          : chr [1:1384617] "Bulgarian Yogurt" "Organic 4% Milk Fat Whole Milk Cottage Cheese" "Organic Celery Hearts" "Cucumber Kirby" ...
    ##  $ aisle_id              : int [1:1384617] 120 108 83 83 95 24 24 21 2 115 ...
    ##  $ department_id         : int [1:1384617] 16 16 4 4 15 4 4 16 16 7 ...
    ##  $ aisle                 : chr [1:1384617] "yogurt" "other creams cheeses" "fresh vegetables" "fresh vegetables" ...
    ##  $ department            : chr [1:1384617] "dairy eggs" "dairy eggs" "produce" "produce" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   order_id = col_integer(),
    ##   ..   product_id = col_integer(),
    ##   ..   add_to_cart_order = col_integer(),
    ##   ..   reordered = col_integer(),
    ##   ..   user_id = col_integer(),
    ##   ..   eval_set = col_character(),
    ##   ..   order_number = col_integer(),
    ##   ..   order_dow = col_integer(),
    ##   ..   order_hour_of_day = col_integer(),
    ##   ..   days_since_prior_order = col_integer(),
    ##   ..   product_name = col_character(),
    ##   ..   aisle_id = col_integer(),
    ##   ..   department_id = col_integer(),
    ##   ..   aisle = col_character(),
    ##   ..   department = col_character()
    ##   .. )

``` r
nrow(instacart) # Number of rows
```

    ## [1] 1384617

``` r
ncol(instacart) # Number of columns
```

    ## [1] 15

``` r
# View dataset dimensions
dim(instacart) # Dimensions of the dataset
```

    ## [1] 1384617      15

``` r
# Show example observations
head(instacart)
```

    ## # A tibble: 6 × 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1        1      49302                 1         1  112108 train               4
    ## 2        1      11109                 2         1  112108 train               4
    ## 3        1      10246                 3         0  112108 train               4
    ## 4        1      49683                 4         0  112108 train               4
    ## 5        1      43633                 5         1  112108 train               4
    ## 6        1      13176                 6         0  112108 train               4
    ## # ℹ 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

``` r
tail(instacart)
```

    ## # A tibble: 6 × 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1  3421063      13565                 2         1  169679 train              30
    ## 2  3421063      14233                 3         1  169679 train              30
    ## 3  3421063      35548                 4         1  169679 train              30
    ## 4  3421070      35951                 1         1  139822 train              15
    ## 5  3421070      16953                 2         1  139822 train              15
    ## 6  3421070       4724                 3         1  139822 train              15
    ## # ℹ 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

<!-- Write a description:
The dataset contains ___ rows and ___ columns. Main variables include:
- 
- 
- 
&#10;Example observations:
&#10;
-->

The dataset contains **1384617** rows and **15** columns. Main variables
include: - `order_id`: Unique identifier for each order - `product_id`:
Unique identifier for each product - `add_to_cart_order`: Order in which
the product was added to the cart - `reordered`: Whether the product was
reordered (1) or not (0) - `user_id`: Unique identifier for each user -
`order_number`: Order number for each user - `eval_set`: Evaluation set
(train, test, or prior) to which the order belongs

Example observations:

``` r
head(instacart)
```

    ## # A tibble: 6 × 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1        1      49302                 1         1  112108 train               4
    ## 2        1      11109                 2         1  112108 train               4
    ## 3        1      10246                 3         0  112108 train               4
    ## 4        1      49683                 4         0  112108 train               4
    ## 5        1      43633                 5         1  112108 train               4
    ## 6        1      13176                 6         0  112108 train               4
    ## # ℹ 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

### How many aisles, and which are most popular?

``` r
# Count total number of aisles
n_distinct(instacart$aisle)
```

    ## [1] 134

``` r
# Find aisles with most orders
instacart %>%
  group_by(aisle) %>%
  summarize(order_count = n()) %>%
  arrange(desc(order_count))
```

    ## # A tibble: 134 × 2
    ##    aisle                         order_count
    ##    <chr>                               <int>
    ##  1 fresh vegetables                   150609
    ##  2 fresh fruits                       150473
    ##  3 packaged vegetables fruits          78493
    ##  4 yogurt                              55240
    ##  5 packaged cheese                     41699
    ##  6 water seltzer sparkling water       36617
    ##  7 milk                                32644
    ##  8 chips pretzels                      31269
    ##  9 soy lactosefree                     26240
    ## 10 bread                               23635
    ## # ℹ 124 more rows

There are **134** aisles in the dataset. The most popular aisles are
fresh vegetables and fresh fruits, with over 150,000 items ordered from
each.

### Plot: Items ordered in each aisle (\>10000 items)

``` r
# Filter and count aisles with >10000 items
aisles_filtered <- instacart %>%
  group_by(aisle) %>%
  summarize(order_count = n()) %>%
  filter(order_count > 10000)

# Create plot
ggplot(aisles_filtered, aes(x = reorder(aisle, order_count), y = order_count)) +
  geom_col() +
  coord_flip() +
  labs(title = "Items Ordered in Each Aisle (>10000 items)",
       x = "Aisle",
       y = "Number of Items Ordered")
```

![](p8105_hw3_xl3493_files/figure-gfm/plot_aisles-1.png)<!-- -->

The plot shows that fresh vegetables and fresh fruits are by far the
most popular aisles. Most aisles with over 10,000 items fall into
produce, dairy, and snack categories. The ordering makes it easy to
identify the top sellers.

### Table: Top 3 items in specific aisles

``` r
# Filter the three specified aisles and find most popular products
top_items <- instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle, product_name) %>%
  summarize(n_orders = n(), .groups = "drop") %>%
  group_by(aisle) %>%
  slice_max(n_orders, n = 3) %>%
  arrange(aisle, desc(n_orders))

# Create table
knitr::kable(top_items, 
             caption = "Top 3 Items in Selected Aisles")
```

| aisle | product_name | n_orders |
|:---|:---|---:|
| baking ingredients | Light Brown Sugar | 499 |
| baking ingredients | Pure Baking Soda | 387 |
| baking ingredients | Cane Sugar | 336 |
| dog food care | Snack Sticks Chicken & Rice Recipe Dog Treats | 30 |
| dog food care | Organix Chicken & Brown Rice Recipe | 28 |
| dog food care | Small Dog Biscuits | 26 |
| packaged vegetables fruits | Organic Baby Spinach | 9784 |
| packaged vegetables fruits | Organic Raspberries | 5546 |
| packaged vegetables fruits | Organic Blueberries | 4966 |

Top 3 Items in Selected Aisles

Light brown sugar is the most popular baking ingredient with 499 orders.
In dog food care, Snack Sticks Chicken & Rice Recipe leads with 30
orders. For packaged vegetables and fruits, organic baby spinach
dominates with 9,784 orders.

### Table: Mean hour of purchase for specific items

``` r
# Filter products and calculate mean purchase time
mean_hour_data <- instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hour = mean(order_hour_of_day), .groups = "drop")

# Convert to wide format table
mean_hour_table <- mean_hour_data %>%
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour
  ) %>%
  rename(
    Product = product_name,
    Sun = `0`, Mon = `1`, Tue = `2`, Wed = `3`,
    Thu = `4`, Fri = `5`, Sat = `6`
  )

# Format table
knitr::kable(mean_hour_table, 
             digits = 2,
             caption = "Mean Hour of Day for Product Orders")
```

| Product          |   Sun |   Mon |   Tue |   Wed |   Thu |   Fri |   Sat |
|:-----------------|------:|------:|------:|------:|------:|------:|------:|
| Coffee Ice Cream | 13.77 | 14.32 | 15.38 | 15.32 | 15.22 | 12.26 | 13.83 |
| Pink Lady Apples | 13.44 | 11.36 | 11.70 | 14.25 | 11.55 | 12.78 | 11.94 |

Mean Hour of Day for Product Orders

Both products are typically purchased in the afternoon, with mean hours
ranging from about 11 to 15. Pink Lady Apples tend to be ordered
slightly earlier in the day compared to Coffee Ice Cream, particularly
on weekdays.

------------------------------------------------------------------------

## Problem 2: Zillow Rental Data Analysis

This problem analyzes rental price trends across New York City ZIP codes
using Zillow data.

### Import and clean the data

``` r
library(janitor)

# Read ZIP code data
zip_codes <- read_csv("../homework_2/data/zillow_data/Zip Codes.csv") %>%
  clean_names() %>%
  rename(zip = zip_code, borough = county) %>%
  select(zip, borough, neighborhood)

# Read rental price data
rental_data <- read_csv("../homework_2/data/zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") %>%
  clean_names() %>%
  select(region_name, starts_with("x")) %>%
  rename(zip = region_name) %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "date",
    values_to = "rental_price",
    names_prefix = "x"
  ) %>%
  mutate(
    date = as.Date(date, format = "%Y_%m_%d"),
    year = year(date),
    month = month(date)
  ) %>%
  filter(date >= as.Date("2015-01-01"), date <= as.Date("2024-08-31"))

# Merge datasets
rental_combined <- rental_data %>%
  left_join(zip_codes, by = "zip") %>%
  filter(!is.na(borough))
```

### ZIP code observation frequency

``` r
# Count observations for each ZIP code
zip_freq <- rental_combined %>%
  count(zip, name = "n_obs")

# Count ZIP codes observed 116 times
full_obs <- zip_freq %>% filter(n_obs == 116) %>% nrow()

# Count ZIP codes observed fewer than 10 times
rare_obs <- zip_freq %>% filter(n_obs < 10) %>% nrow()
```

**147** ZIP codes are observed all 116 times (complete data from Jan
2015 to Aug 2024). **0** ZIP codes are observed fewer than 10 times.

Some ZIP codes are observed rarely because: 1. They may be primarily
commercial or industrial areas with limited residential rental
properties 2. Zillow may exclude areas with insufficient market data to
calculate reliable rent indices 3. Some neighborhoods have predominantly
public housing or rent-controlled units not reflected in market rates

### Table: Average rental price by borough and year

``` r
# Calculate average rental price by borough and year
borough_year_avg <- rental_combined %>%
  group_by(borough, year) %>%
  summarize(avg_rent = mean(rental_price, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(
    names_from = year,
    values_from = avg_rent
  )

# Create table
knitr::kable(borough_year_avg, 
             digits = 0,
             caption = "Average Rental Price by Borough and Year")
```

| borough  | 2015 | 2016 | 2017 | 2018 | 2019 | 2020 | 2021 | 2022 | 2023 | 2024 |
|:---------|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|
| Bronx    | 1760 | 1520 | 1544 | 1639 | 1706 | 1811 | 1858 | 2054 | 2285 | 2497 |
| Kings    | 2493 | 2520 | 2546 | 2547 | 2631 | 2555 | 2550 | 2868 | 3015 | 3126 |
| New York | 3006 | 3015 | 3109 | 3160 | 3285 | 3091 | 3124 | 3753 | 3908 | 4053 |
| Queens   | 2215 | 2272 | 2263 | 2292 | 2388 | 2316 | 2211 | 2406 | 2562 | 2694 |
| Richmond |  NaN |  NaN |  NaN |  NaN |  NaN | 1978 | 2045 | 2147 | 2333 | 2536 |

Average Rental Price by Borough and Year

Rental prices generally increased from 2015 to 2019 across most
boroughs, though with some fluctuations. The Bronx experienced a decline
in 2016 before resuming growth. During 2020-2021, Manhattan and Brooklyn
showed notable declines, likely due to COVID-19. Prices have since
recovered and continued rising. Manhattan consistently has the highest
rents, followed by Brooklyn. The Bronx and Staten Island have the most
affordable rents.

### Plot: NYC rental prices by ZIP code across years

``` r
# Create rental price trend plot
plot_trends <- ggplot(rental_combined, aes(x = date, y = rental_price, group = zip)) +
  geom_line(alpha = 0.3, size = 0.3) +
  facet_wrap(~borough, scales = "free_y") +
  labs(
    title = "NYC Rental Price Trends by ZIP Code (2015-2024)",
    x = "Date",
    y = "Rental Price ($)"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot_trends
```

![](p8105_hw3_xl3493_files/figure-gfm/plot_rental_trends-1.png)<!-- -->

The plot reveals several trends: 1. Manhattan experienced a clear dip
during 2020-2021 (pandemic), with significant variation across ZIP codes
2. Brooklyn shows similar patterns but with less dramatic drops 3.
Queens, Bronx, and Staten Island show more stable, gradual increases

Manhattan has the highest price range and variability. All boroughs show
recovery and growth post-2021.

### Plot: Distribution of 2023 rental prices by borough

``` r
# Calculate average rental price for each ZIP code in 2023
rental_2023 <- rental_combined %>%
  filter(year == 2023) %>%
  group_by(borough, zip) %>%
  summarize(avg_rent = mean(rental_price, na.rm = TRUE), .groups = "drop")

# Create distribution plot
plot_distribution <- ggplot(rental_2023, aes(x = borough, y = avg_rent, fill = borough)) +
  geom_boxplot() +
  labs(
    title = "Distribution of Average 2023 Rental Prices by Borough",
    x = "Borough",
    y = "Average Rental Price ($)"
  ) +
  theme_minimal() +
  theme(legend.position = "none")

plot_distribution
```

![](p8105_hw3_xl3493_files/figure-gfm/plot_2023_distribution-1.png)<!-- -->

Manhattan has the highest median rent (~\$3,800) with substantial
variation and several high-end outliers exceeding \$6,000. Brooklyn
follows with median around \$3,200. Queens, Bronx, and Staten Island
cluster in the \$2,000-\$2,500 range with less variation and fewer
outliers.

### Combined plot and export

``` r
library(patchwork)

# Create results folder
if (!dir.exists("results")) {
    dir.create("results")
}

# Combine the two previous plots
combined_plot <- plot_trends / plot_distribution

# Export plot
ggsave("results/zillow_rental_analysis.png", 
       combined_plot, 
       width = 12, 
       height = 10)

combined_plot
```

![](p8105_hw3_xl3493_files/figure-gfm/combine_and_export-1.png)<!-- -->

------------------------------------------------------------------------

## Problem 3: NHANES Accelerometer Data

This problem analyzes physical activity patterns using accelerometer
data from the NHANES study.

### Load and tidy the datasets

``` r
# NOTE: Download data files from the links provided in homework instructions
# Save nhanes_covar.csv and nhanes_accel.csv to the data/ folder before running

# Read demographic data
demographic <- read_csv("data/nhanes_covar.csv", skip = 4) %>%
  clean_names() %>%
  filter(age >= 21) %>%
  drop_na() %>%
  mutate(
    sex = factor(sex, levels = c(1, 2), labels = c("Male", "Female")),
    education = factor(education, 
                      levels = c(1, 2, 3),
                      labels = c("Less than high school", 
                                "High school equivalent", 
                                "More than high school"))
  )

# Read accelerometer data
accelerometer <- read_csv("data/nhanes_accel.csv") %>%
  clean_names()

# Merge datasets
nhanes_data <- demographic %>%
  inner_join(accelerometer, by = "seqn")
```

### Table and visualization: Demographics by education

``` r
# Create participant count table
demographics_summary <- nhanes_data %>%
  group_by(education, sex) %>%
  summarize(count = n(), .groups = "drop") %>%
  pivot_wider(
    names_from = sex,
    values_from = count
  )

knitr::kable(demographics_summary, 
             caption = "Number of Participants by Education and Sex")
```

| education              | Male | Female |
|:-----------------------|-----:|-------:|
| Less than high school  |   27 |     28 |
| High school equivalent |   35 |     23 |
| More than high school  |   56 |     59 |

Number of Participants by Education and Sex

``` r
# Create age distribution visualization
ggplot(nhanes_data, aes(x = age, fill = sex)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~education) +
  labs(
    title = "Age Distribution by Education Level and Sex",
    x = "Age (years)",
    y = "Density",
    fill = "Sex"
  ) +
  theme_minimal()
```

![](p8105_hw3_xl3493_files/figure-gfm/demographics_plot-1.png)<!-- -->

The distribution shows more participants with education beyond high
school. Age distributions are fairly similar across education levels,
though those with less than high school education tend to be slightly
older. Gender balance is relatively even across all education
categories.

### Plot: Total activity vs age

``` r
# Calculate total activity for each participant
total_activity <- nhanes_data %>%
  mutate(
    total_activity = rowSums(select(., starts_with("min")))
  )

# Create total activity vs age plot
ggplot(total_activity, aes(x = age, y = total_activity, color = sex)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "loess", se = FALSE) +
  facet_wrap(~education) +
  labs(
    title = "Total Daily Activity by Age, Education, and Sex",
    x = "Age (years)",
    y = "Total Activity (MIMS)",
    color = "Sex"
  ) +
  theme_minimal()
```

![](p8105_hw3_xl3493_files/figure-gfm/total_activity_plot-1.png)<!-- -->

Total activity generally decreases with age across all education levels.
Women tend to have slightly higher activity than men, particularly in
the “More than high school” category. The decline in activity with age
appears steepest for those with less than high school education.

### Plot: 24-hour activity time courses

``` r
# Prepare time series data
activity_by_time <- nhanes_data %>%
  pivot_longer(
    cols = starts_with("min"),
    names_to = "minute",
    values_to = "mims",
    names_prefix = "min"
  ) %>%
  mutate(
    minute = as.numeric(minute),
    hour = minute / 60
  ) %>%
  group_by(education, sex, minute) %>%
  summarize(mean_mims = mean(mims, na.rm = TRUE), .groups = "drop") %>%
  mutate(hour = minute / 60)

# Create 24-hour activity pattern plot
ggplot(activity_by_time, aes(x = hour, y = mean_mims, color = sex)) +
  geom_smooth(se = FALSE, size = 1) +
  facet_wrap(~education) +
  labs(
    title = "24-Hour Activity Patterns by Education and Sex",
    x = "Hour of Day",
    y = "Average Activity (MIMS)",
    color = "Sex"
  ) +
  scale_x_continuous(breaks = seq(0, 24, 4)) +
  theme_minimal()
```

![](p8105_hw3_xl3493_files/figure-gfm/activity_time_course-1.png)<!-- -->

All groups show similar daily patterns: low activity during sleeping
hours (midnight to ~5am), rising activity in the morning, and peaks
during midday and early evening. Those with more education show slightly
higher midday activity. Women tend to have higher activity levels
throughout the day, especially during waking hours. The late evening
drop-off (around 8-9pm) is consistent across all groups.

------------------------------------------------------------------------
