Homework 6
================
Xuange Liang (xl3493)
2025-12-03

- [0.1 Problem 1: Homicide Data Analysis with Logistic
  Regression](#01-problem-1-homicide-data-analysis-with-logistic-regression)
- [0.2 Problem 2: Bootstrap Analysis of Weather
  Data](#02-problem-2-bootstrap-analysis-of-weather-data)
- [0.3 Problem 3: Birthweight
  Analysis](#03-problem-3-birthweight-analysis)
- [0.4 Session Info](#04-session-info)

## 0.1 Problem 1: Homicide Data Analysis with Logistic Regression

### 0.1.1 Loading required libraries

``` r
library(tidyverse)
library(broom)
library(modelr)
library(purrr)
set.seed(999)
```

### 0.1.2 Loading and cleaning the data

``` r
# Load data from Washington Post GitHub repository
homicide_data <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

# View structure
head(homicide_data)
```

    ## # A tibble: 6 × 12
    ##   uid   reported_date victim_last victim_first victim_race victim_age victim_sex
    ##   <chr>         <dbl> <chr>       <chr>        <chr>       <chr>      <chr>     
    ## 1 Alb-…      20100504 GARCIA      JUAN         Hispanic    78         Male      
    ## 2 Alb-…      20100216 MONTOYA     CAMERON      Hispanic    17         Male      
    ## 3 Alb-…      20100601 SATTERFIELD VIVIANA      White       15         Female    
    ## 4 Alb-…      20100101 MENDIOLA    CARLOS       Hispanic    32         Male      
    ## 5 Alb-…      20100102 MULA        VIVIAN       White       72         Female    
    ## 6 Alb-…      20100126 BOOK        GERALDINE    White       91         Female    
    ## # ℹ 5 more variables: city <chr>, state <chr>, lat <dbl>, lon <dbl>,
    ## #   disposition <chr>

``` r
str(homicide_data)
```

    ## spc_tbl_ [52,179 × 12] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ uid          : chr [1:52179] "Alb-000001" "Alb-000002" "Alb-000003" "Alb-000004" ...
    ##  $ reported_date: num [1:52179] 20100504 20100216 20100601 20100101 20100102 ...
    ##  $ victim_last  : chr [1:52179] "GARCIA" "MONTOYA" "SATTERFIELD" "MENDIOLA" ...
    ##  $ victim_first : chr [1:52179] "JUAN" "CAMERON" "VIVIANA" "CARLOS" ...
    ##  $ victim_race  : chr [1:52179] "Hispanic" "Hispanic" "White" "Hispanic" ...
    ##  $ victim_age   : chr [1:52179] "78" "17" "15" "32" ...
    ##  $ victim_sex   : chr [1:52179] "Male" "Male" "Female" "Male" ...
    ##  $ city         : chr [1:52179] "Albuquerque" "Albuquerque" "Albuquerque" "Albuquerque" ...
    ##  $ state        : chr [1:52179] "NM" "NM" "NM" "NM" ...
    ##  $ lat          : num [1:52179] 35.1 35.1 35.1 35.1 35.1 ...
    ##  $ lon          : num [1:52179] -107 -107 -107 -107 -107 ...
    ##  $ disposition  : chr [1:52179] "Closed without arrest" "Closed by arrest" "Closed without arrest" "Closed by arrest" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   uid = col_character(),
    ##   ..   reported_date = col_double(),
    ##   ..   victim_last = col_character(),
    ##   ..   victim_first = col_character(),
    ##   ..   victim_race = col_character(),
    ##   ..   victim_age = col_character(),
    ##   ..   victim_sex = col_character(),
    ##   ..   city = col_character(),
    ##   ..   state = col_character(),
    ##   ..   lat = col_double(),
    ##   ..   lon = col_double(),
    ##   ..   disposition = col_character()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

### 0.1.3 Data cleaning and preparation

``` r
homicide_clean <- homicide_data %>%
  mutate(
    city_state = str_c(city, state, sep = ", "), # Create city_state variable

    resolved = as.numeric(disposition == "Closed by arrest"), # Binary solved variable
    victim_age = as.numeric(victim_age) # Convert victim_age to numeric

  ) %>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"), # Omit specified cities

    victim_race %in% c("White", "Black")  # Filter for white/black victims

  ) %>%
  select(city_state, resolved, victim_age, victim_sex, victim_race)

# View cleaned data
head(homicide_clean)
```

    ## # A tibble: 6 × 5
    ##   city_state      resolved victim_age victim_sex victim_race
    ##   <chr>              <dbl>      <dbl> <chr>      <chr>      
    ## 1 Albuquerque, NM        0         15 Female     White      
    ## 2 Albuquerque, NM        0         72 Female     White      
    ## 3 Albuquerque, NM        0         91 Female     White      
    ## 4 Albuquerque, NM        0         56 Male       White      
    ## 5 Albuquerque, NM        0         NA Male       White      
    ## 6 Albuquerque, NM        1         43 Female     White

``` r
summary(homicide_clean)
```

    ##   city_state           resolved        victim_age      victim_sex       
    ##  Length:39693       Min.   :0.0000   Min.   :  0.00   Length:39693      
    ##  Class :character   1st Qu.:0.0000   1st Qu.: 22.00   Class :character  
    ##  Mode  :character   Median :0.0000   Median : 28.00   Mode  :character  
    ##                     Mean   :0.4893   Mean   : 31.93                     
    ##                     3rd Qu.:1.0000   3rd Qu.: 40.00                     
    ##                     Max.   :1.0000   Max.   :102.00                     
    ##                                      NA's   :290                        
    ##  victim_race       
    ##  Length:39693      
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ##                    
    ## 

**Description of cleaned data:**

The cleaned homicide dataset contains 39,693 observations across 5
variables after applying the required filters. We created a `city_state`
variable combining city and state, and a binary `resolved` variable
indicating whether the homicide was solved (1 = Closed by arrest, 0 =
otherwise). We excluded Dallas, TX; Phoenix, AZ; Kansas City, MO; and
Tulsa, AL as specified, and limited our analysis to cases where the
victim’s race was White or Black. The `victim_age` variable was
converted to numeric. The dataset includes 19,420 resolved cases and
20,273 unresolved cases. Among victims, 33,749 are male, 5,903 are
female, and 41 have unknown sex. The racial distribution shows 33,361
Black victims and 6,332 White victims.

### 0.1.4 Logistic regression for Baltimore, MD

``` r
# Filter Baltimore data
baltimore_data <- homicide_clean %>%
  filter(city_state == "Baltimore, MD")

# Fit logistic regression
baltimore_fit <- glm(
  resolved ~ victim_age + victim_sex + victim_race,
  data = baltimore_data,
  family = binomial()
)

# Tidy the results
baltimore_tidy <- baltimore_fit %>%
  broom::tidy() %>%
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>%
  select(term, estimate, OR, CI_lower, CI_upper, p.value)

# View results
baltimore_tidy
```

    ## # A tibble: 4 × 6
    ##   term             estimate    OR CI_lower CI_upper  p.value
    ##   <chr>               <dbl> <dbl>    <dbl>    <dbl>    <dbl>
    ## 1 (Intercept)       0.310   1.36     0.975    1.91  7.04e- 2
    ## 2 victim_age       -0.00673 0.993    0.987    1.000 4.30e- 2
    ## 3 victim_sexMale   -0.854   0.426    0.325    0.558 6.26e-10
    ## 4 victim_raceWhite  0.842   2.32     1.65     3.27  1.45e- 6

``` r
# Extract OR and CI for male vs female comparison
baltimore_male_OR <- baltimore_tidy %>%
  filter(term == "victim_sexMale")
```

**Interpretation for Baltimore, MD:**

For the city of Baltimore, MD, the adjusted odds ratio for solving
homicides comparing male victims to female victims is 0.426 (95% CI:
0.325, 0.558). This means that, holding victim age and race constant,
homicides with male victims have 0.426 times the odds of being resolved
compared to homicides with female victims. In other words, homicides
with male victims are significantly less likely to be solved than those
with female victims. The confidence interval does not include 1,
indicating this difference is statistically significant at the 0.05
level (p \< 0.001).

### 0.1.5 Logistic regression for all cities

``` r
# Function to fit logistic regression and extract OR for victim_sex
fit_logistic <- function(df) {
  # Fit model
  fit <- glm(
    resolved ~ victim_age + victim_sex + victim_race,
    data = df,
    family = binomial()
  )

  # Tidy and extract male vs female OR
  fit %>%
    broom::tidy() %>%
    filter(term == "victim_sexMale") %>%
    mutate(
      OR = exp(estimate),
      CI_lower = exp(estimate - 1.96 * std.error),
      CI_upper = exp(estimate + 1.96 * std.error)
    ) %>%
    select(term, OR, CI_lower, CI_upper)
}

# Run logistic regression for each city
all_cities_results <- homicide_clean %>%
  nest(data = -city_state) %>%
  mutate(
    model_results = map(data, fit_logistic)
  ) %>%
  select(-data) %>%
  unnest(model_results)

# View results
head(all_cities_results)
```

    ## # A tibble: 6 × 5
    ##   city_state      term              OR CI_lower CI_upper
    ##   <chr>           <chr>          <dbl>    <dbl>    <dbl>
    ## 1 Albuquerque, NM victim_sexMale 1.77     0.831    3.76 
    ## 2 Atlanta, GA     victim_sexMale 1.00     0.684    1.46 
    ## 3 Baltimore, MD   victim_sexMale 0.426    0.325    0.558
    ## 4 Baton Rouge, LA victim_sexMale 0.381    0.209    0.695
    ## 5 Birmingham, AL  victim_sexMale 0.870    0.574    1.32 
    ## 6 Boston, MA      victim_sexMale 0.674    0.356    1.28

### 0.1.6 Plot: Odds ratios and confidence intervals by city

``` r
# Create plot
or_plot <- all_cities_results %>%
  mutate(
    city_state = fct_reorder(city_state, OR)
  ) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_point(color = "steelblue", size = 2) +
  geom_errorbar(
    aes(ymin = CI_lower, ymax = CI_upper),
    width = 0.3,
    color = "steelblue",
    alpha = 0.6
  ) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "red", alpha = 0.5) +
  coord_flip() +
  labs(
    title = "Adjusted Odds Ratios for Solving Homicides: Male vs Female Victims",
    subtitle = "Error bars represent 95% confidence intervals",
    x = "City, State",
    y = "Adjusted Odds Ratio (Male vs Female)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    axis.text.y = element_text(size = 8)
  )

or_plot
```

![](p8105_hw6_xl3493_files/figure-gfm/or_plot-1.png)<!-- -->

1.  **Overall Pattern**: Most cities show ORs below 1 (indicated by the
    red dashed reference line), suggesting that in most cities,
    homicides with male victims are less likely to be solved than those
    with female victims, after adjusting for victim age and race.

2.  **Lowest ORs**: New York, NY has the lowest OR (0.262), followed by
    Baton Rouge, LA (0.381) and Omaha, NE (0.382). In these cities, male
    victim homicides are dramatically less likely to be solved compared
    to female victim homicides.

3.  **Highest ORs**: Albuquerque, NM shows the highest OR (1.77). In
    this city, the pattern reverses, with male victim homicides actually
    having higher odds of being solved, though the confidence intervals
    are wide and include 1, suggesting these differences may not be
    statistically significant.

4.  **Statistical Significance**: For most cities, the confidence
    intervals do not include 1, indicating statistically significant
    differences in resolution rates between male and female victim
    homicides.

------------------------------------------------------------------------

## 0.2 Problem 2: Bootstrap Analysis of Weather Data

### 0.2.1 Loading the weather data

``` r
library(p8105.datasets)
data("weather_df")

# Filter for Central Park data only
weather_df <- weather_df %>%
  filter(name == "CentralPark_NY") %>%
  select(date, tmax, tmin, prcp)

# View data structure
head(weather_df)
```

    ## # A tibble: 6 × 4
    ##   date        tmax  tmin  prcp
    ##   <date>     <dbl> <dbl> <dbl>
    ## 1 2021-01-01   4.4   0.6   157
    ## 2 2021-01-02  10.6   2.2    13
    ## 3 2021-01-03   3.3   1.1    56
    ## 4 2021-01-04   6.1   1.7     5
    ## 5 2021-01-05   5.6   2.2     0
    ## 6 2021-01-06   5     1.1     0

``` r
str(weather_df)
```

    ## tibble [730 × 4] (S3: tbl_df/tbl/data.frame)
    ##  $ date: Date[1:730], format: "2021-01-01" "2021-01-02" ...
    ##  $ tmax: num [1:730] 4.4 10.6 3.3 6.1 5.6 5 5 2.8 2.8 5 ...
    ##  $ tmin: num [1:730] 0.6 2.2 1.1 1.7 2.2 1.1 -1 -2.7 -4.3 -1.6 ...
    ##  $ prcp: num [1:730] 157 13 56 5 0 0 0 0 0 0 ...

### 0.2.2 Bootstrap function

``` r
# Function to perform one bootstrap sample and calculate r^2 and log(beta1*beta2)
bootstrap_analysis <- function(df) {
  # Sample with replacement
  boot_sample <- sample_frac(df, replace = TRUE)

  # Fit linear model: tmax ~ tmin + prcp
  fit <- lm(tmax ~ tmin + prcp, data = boot_sample)

  # Extract r^2 using broom::glance()
  r_squared <- fit %>%
    broom::glance() %>%
    pull(r.squared)

  # Extract beta1 and beta2 using broom::tidy()
  beta_estimates <- fit %>%
    broom::tidy() %>%
    filter(term %in% c("tmin", "prcp")) %>%
    pull(estimate)

  # Calculate log(beta1 * beta2)
  # Handle cases where product might be negative or zero
  beta_product <- beta_estimates[1] * beta_estimates[2]
  log_beta_product <- ifelse(beta_product > 0, log(beta_product), NA)

  tibble(
    r_squared = r_squared,
    log_beta_product = log_beta_product
  )
}

bootstrap_analysis(weather_df)
```

    ## # A tibble: 1 × 2
    ##   r_squared log_beta_product
    ##       <dbl> <lgl>           
    ## 1     0.910 NA

### 0.2.3 Running 5000 bootstrap samples

``` r
bootstrap_results <- tibble(
  iteration = 1:5000
) %>%
  mutate(
    results = map(iteration, ~bootstrap_analysis(weather_df))
  ) %>%
  unnest(results)

head(bootstrap_results)
```

    ## # A tibble: 6 × 3
    ##   iteration r_squared log_beta_product
    ##       <int>     <dbl>            <dbl>
    ## 1         1     0.910            NA   
    ## 2         2     0.915            NA   
    ## 3         3     0.926            NA   
    ## 4         4     0.908            NA   
    ## 5         5     0.893            -8.67
    ## 6         6     0.922            NA

``` r
summary(bootstrap_results)
```

    ##    iteration      r_squared      log_beta_product 
    ##  Min.   :   1   Min.   :0.8774   Min.   :-15.116  
    ##  1st Qu.:1251   1st Qu.:0.9071   1st Qu.: -8.198  
    ##  Median :2500   Median :0.9134   Median : -7.378  
    ##  Mean   :2500   Mean   :0.9127   Mean   : -7.559  
    ##  3rd Qu.:3750   3rd Qu.:0.9187   3rd Qu.: -6.725  
    ##  Max.   :5000   Max.   :0.9383   Max.   : -5.041  
    ##                                  NA's   :4469

### 0.2.4 Distribution plots

``` r
# Plot distribution of r^2
r2_plot <- bootstrap_results %>%
  ggplot(aes(x = r_squared)) +
  geom_histogram(bins = 50, fill = "steelblue", alpha = 0.7) +
  geom_vline(
    xintercept = mean(bootstrap_results$r_squared),
    linetype = "dashed",
    color = "red",
    linewidth = 1
  ) +
  labs(
    title = "Distribution of Bootstrap Estimates: R²",
    subtitle = paste("Mean =", round(mean(bootstrap_results$r_squared), 4)),
    x = "R²",
    y = "Frequency"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"))

r2_plot
```

![](p8105_hw6_xl3493_files/figure-gfm/distribution_plots-1.png)<!-- -->

``` r
# Plot distribution of log(beta1*beta2)
log_beta_plot <- bootstrap_results %>%
  filter(!is.na(log_beta_product)) %>%
  ggplot(aes(x = log_beta_product)) +
  geom_histogram(bins = 50, fill = "darkgreen", alpha = 0.7) +
  geom_vline(
    xintercept = mean(bootstrap_results$log_beta_product, na.rm = TRUE),
    linetype = "dashed",
    color = "red",
    linewidth = 1
  ) +
  labs(
    title = "Distribution of Bootstrap Estimates: log(β₁×β₂)",
    subtitle = paste("Mean =", round(mean(bootstrap_results$log_beta_product, na.rm = TRUE), 4)),
    x = "log(β₁×β₂)",
    y = "Frequency"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"))

log_beta_plot
```

![](p8105_hw6_xl3493_files/figure-gfm/distribution_plots-2.png)<!-- -->

**Description of distributions:**

**Distribution of R²**: The bootstrap distribution of R² estimates is
approximately normal and centered around 0.913 (mean = 0.913, median =
0.913). The distribution is relatively narrow with a standard deviation
of 0.0086, indicating that the R² estimate is quite stable across
bootstrap samples. The distribution shows slight left skewness, with
values ranging roughly from 0.87 to 0.94. This high R² value indicates
that `tmin` and `prcp` together explain about 91% of the variability in
`tmax`, demonstrating a very strong linear relationship.

**Distribution of log(β̂₁×β̂₂)**: The bootstrap distribution of log(β̂₁×β̂₂)
appears to be left-skewed with a long left tail (mean = -7.56, median =
-7.38). The distribution has considerable spread (SD = 1.24) and ranges
approximately from -12 to -4. Notably, there are 4,469 NA values (out of
5,000 bootstrap samples, approximately 89%), which occur when the
product β̂₁×β̂₂ is negative. This happens because while the coefficient
for `tmin` (β̂₁) is positive, the coefficient for `prcp` (β̂₂) is
typically negative (more precipitation is associated with lower maximum
temperature when controlling for minimum temperature), making their
product negative and the log undefined. The distribution we observe
represents only those samples where both coefficients happened to have
the same sign.

### 0.2.5 95% Confidence Intervals

``` r
# Calculate 95% CI for r^2
r2_ci <- bootstrap_results %>%
  summarize(
    lower_ci = quantile(r_squared, 0.025),
    upper_ci = quantile(r_squared, 0.975)
  )

# Calculate 95% CI for log(beta1*beta2)
log_beta_ci <- bootstrap_results %>%
  filter(!is.na(log_beta_product)) %>%
  summarize(
    lower_ci = quantile(log_beta_product, 0.025),
    upper_ci = quantile(log_beta_product, 0.975)
  )

# Display results
cat("95% CI for R²:", r2_ci$lower_ci, "to", r2_ci$upper_ci, "\n")
```

    ## 95% CI for R²: 0.8946572 to 0.9279384

``` r
cat("95% CI for log(β₁×β₂):", log_beta_ci$lower_ci, "to", log_beta_ci$upper_ci, "\n")
```

    ## 95% CI for log(β₁×β₂): -10.61181 to -5.630128

**95% CI for R²**: (0.895, 0.928). We are 95% confident that the true
proportion of variability in maximum temperature explained by minimum
temperature and precipitation falls between 0.895 and 0.928.

**95% CI for log(β̂₁×β̂₂)**: (-10.61, -5.63). Among the bootstrap samples
where the product β̂₁×β̂₂ was positive (allowing the log transformation),
we are 95% confident that the true value of log(β̂₁×β̂₂) falls between
-10.61 and -5.63.

------------------------------------------------------------------------

## 0.3 Problem 3: Birthweight Analysis

### 0.3.1 Loading and cleaning the data

``` r
# Load birthweight data
birthweight_data <- read_csv("https://p8105.com/data/birthweight.csv")

# View structure
head(birthweight_data)
```

    ## # A tibble: 6 × 20
    ##   babysex bhead blength   bwt delwt fincome frace gaweeks malform menarche
    ##     <dbl> <dbl>   <dbl> <dbl> <dbl>   <dbl> <dbl>   <dbl>   <dbl>    <dbl>
    ## 1       2    34      51  3629   177      35     1    39.9       0       13
    ## 2       1    34      48  3062   156      65     2    25.9       0       14
    ## 3       2    36      50  3345   148      85     1    39.9       0       12
    ## 4       1    34      52  3062   157      55     1    40         0       14
    ## 5       2    34      52  3374   156       5     1    41.6       0       13
    ## 6       1    33      52  3374   129      55     1    40.7       0       12
    ## # ℹ 10 more variables: mheight <dbl>, momage <dbl>, mrace <dbl>, parity <dbl>,
    ## #   pnumlbw <dbl>, pnumsga <dbl>, ppbmi <dbl>, ppwt <dbl>, smoken <dbl>,
    ## #   wtgain <dbl>

``` r
str(birthweight_data)
```

    ## spc_tbl_ [4,342 × 20] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ babysex : num [1:4342] 2 1 2 1 2 1 2 2 1 1 ...
    ##  $ bhead   : num [1:4342] 34 34 36 34 34 33 33 33 36 33 ...
    ##  $ blength : num [1:4342] 51 48 50 52 52 52 46 49 52 50 ...
    ##  $ bwt     : num [1:4342] 3629 3062 3345 3062 3374 ...
    ##  $ delwt   : num [1:4342] 177 156 148 157 156 129 126 140 146 169 ...
    ##  $ fincome : num [1:4342] 35 65 85 55 5 55 96 5 85 75 ...
    ##  $ frace   : num [1:4342] 1 2 1 1 1 1 2 1 1 2 ...
    ##  $ gaweeks : num [1:4342] 39.9 25.9 39.9 40 41.6 ...
    ##  $ malform : num [1:4342] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ menarche: num [1:4342] 13 14 12 14 13 12 14 12 11 12 ...
    ##  $ mheight : num [1:4342] 63 65 64 64 66 66 72 62 61 64 ...
    ##  $ momage  : num [1:4342] 36 25 29 18 20 23 29 19 13 19 ...
    ##  $ mrace   : num [1:4342] 1 2 1 1 1 1 2 1 1 2 ...
    ##  $ parity  : num [1:4342] 3 0 0 0 0 0 0 0 0 0 ...
    ##  $ pnumlbw : num [1:4342] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ pnumsga : num [1:4342] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ ppbmi   : num [1:4342] 26.3 21.3 23.6 21.8 21 ...
    ##  $ ppwt    : num [1:4342] 148 128 137 127 130 115 105 119 105 145 ...
    ##  $ smoken  : num [1:4342] 0 0 1 10 1 0 0 0 0 4 ...
    ##  $ wtgain  : num [1:4342] 29 28 11 30 26 14 21 21 41 24 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   babysex = col_double(),
    ##   ..   bhead = col_double(),
    ##   ..   blength = col_double(),
    ##   ..   bwt = col_double(),
    ##   ..   delwt = col_double(),
    ##   ..   fincome = col_double(),
    ##   ..   frace = col_double(),
    ##   ..   gaweeks = col_double(),
    ##   ..   malform = col_double(),
    ##   ..   menarche = col_double(),
    ##   ..   mheight = col_double(),
    ##   ..   momage = col_double(),
    ##   ..   mrace = col_double(),
    ##   ..   parity = col_double(),
    ##   ..   pnumlbw = col_double(),
    ##   ..   pnumsga = col_double(),
    ##   ..   ppbmi = col_double(),
    ##   ..   ppwt = col_double(),
    ##   ..   smoken = col_double(),
    ##   ..   wtgain = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
# Check for missing data
sum(is.na(birthweight_data))
```

    ## [1] 0

### 0.3.2 Data cleaning and preparation

``` r
# Convert categorical variables to factors
birthweight_clean <- birthweight_data %>%
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("Male", "Female")),
    frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9),
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown")),
    mrace = factor(mrace, levels = c(1, 2, 3, 4, 8),
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other")),
    malform = factor(malform, levels = c(0, 1), labels = c("Absent", "Present"))
  )

# Check data summary
summary(birthweight_clean)
```

    ##    babysex         bhead          blength           bwt           delwt      
    ##  Male  :2230   Min.   :21.00   Min.   :20.00   Min.   : 595   Min.   : 86.0  
    ##  Female:2112   1st Qu.:33.00   1st Qu.:48.00   1st Qu.:2807   1st Qu.:131.0  
    ##                Median :34.00   Median :50.00   Median :3132   Median :143.0  
    ##                Mean   :33.65   Mean   :49.75   Mean   :3114   Mean   :145.6  
    ##                3rd Qu.:35.00   3rd Qu.:51.00   3rd Qu.:3459   3rd Qu.:157.0  
    ##                Max.   :41.00   Max.   :63.00   Max.   :4791   Max.   :334.0  
    ##     fincome               frace         gaweeks         malform    
    ##  Min.   : 0.00   White       :2123   Min.   :17.70   Absent :4327  
    ##  1st Qu.:25.00   Black       :1911   1st Qu.:38.30   Present:  15  
    ##  Median :35.00   Asian       :  46   Median :39.90                 
    ##  Mean   :44.11   Puerto Rican: 248   Mean   :39.43                 
    ##  3rd Qu.:65.00   Other       :  14   3rd Qu.:41.10                 
    ##  Max.   :96.00   Unknown     :   0   Max.   :51.30                 
    ##     menarche        mheight          momage              mrace     
    ##  Min.   : 0.00   Min.   :48.00   Min.   :12.0   White       :2147  
    ##  1st Qu.:12.00   1st Qu.:62.00   1st Qu.:18.0   Black       :1909  
    ##  Median :12.00   Median :63.00   Median :20.0   Asian       :  43  
    ##  Mean   :12.51   Mean   :63.49   Mean   :20.3   Puerto Rican: 243  
    ##  3rd Qu.:13.00   3rd Qu.:65.00   3rd Qu.:22.0   Other       :   0  
    ##  Max.   :19.00   Max.   :77.00   Max.   :44.0                      
    ##      parity            pnumlbw     pnumsga      ppbmi            ppwt      
    ##  Min.   :0.000000   Min.   :0   Min.   :0   Min.   :13.07   Min.   : 70.0  
    ##  1st Qu.:0.000000   1st Qu.:0   1st Qu.:0   1st Qu.:19.53   1st Qu.:110.0  
    ##  Median :0.000000   Median :0   Median :0   Median :21.03   Median :120.0  
    ##  Mean   :0.002303   Mean   :0   Mean   :0   Mean   :21.57   Mean   :123.5  
    ##  3rd Qu.:0.000000   3rd Qu.:0   3rd Qu.:0   3rd Qu.:22.91   3rd Qu.:134.0  
    ##  Max.   :6.000000   Max.   :0   Max.   :0   Max.   :46.10   Max.   :287.0  
    ##      smoken           wtgain      
    ##  Min.   : 0.000   Min.   :-46.00  
    ##  1st Qu.: 0.000   1st Qu.: 15.00  
    ##  Median : 0.000   Median : 22.00  
    ##  Mean   : 4.145   Mean   : 22.08  
    ##  3rd Qu.: 5.000   3rd Qu.: 28.00  
    ##  Max.   :60.000   Max.   : 89.00

**Description of cleaned data:**

The birthweight dataset contains 4,342 observations with 20 variables
and no missing data. During data cleaning, we converted categorical
variables to factors with meaningful labels: `babysex` (Male/Female),
`frace` (father’s race), `mrace` (mother’s race), and `malform`
(malformation presence). The outcome variable `bwt` (birthweight in
grams) has a mean of approximately 3,114 grams. Key predictors include
continuous variables like `blength` (baby’s length), `bhead` (head
circumference), `gaweeks` (gestational age), `delwt` (mother’s delivery
weight), and `smoken` (average cigarettes per day during pregnancy), as
well as categorical variables for parental race and baby sex.

### 0.3.3 Proposed regression model

``` r
# Proposed model based on hypothesized structure
# Model includes key biological and medical factors affecting birthweight
my_model <- lm(
  bwt ~ blength + gaweeks + bhead + delwt + mrace + smoken + wtgain,
  data = birthweight_clean
)

# View model summary
summary(my_model)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + gaweeks + bhead + delwt + mrace + 
    ##     smoken + wtgain, data = birthweight_clean)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1095.38  -183.31    -4.37   175.12  2333.47 
    ## 
    ## Coefficients:
    ##                     Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)       -5664.3866    98.1899 -57.688  < 2e-16 ***
    ## blength              75.1456     2.0191  37.217  < 2e-16 ***
    ## gaweeks              11.7973     1.4551   8.107 6.67e-16 ***
    ## bhead               129.3125     3.4149  37.868  < 2e-16 ***
    ## delwt                 1.8149     0.2125   8.539  < 2e-16 ***
    ## mraceBlack         -148.6702     9.2292 -16.109  < 2e-16 ***
    ## mraceAsian          -83.3172    42.4240  -1.964   0.0496 *  
    ## mracePuerto Rican  -119.6706    18.7233  -6.392 1.82e-10 ***
    ## smoken               -4.9146     0.5866  -8.378  < 2e-16 ***
    ## wtgain                2.3873     0.4230   5.644 1.77e-08 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 273.3 on 4332 degrees of freedom
    ## Multiple R-squared:  0.7158, Adjusted R-squared:  0.7152 
    ## F-statistic:  1212 on 9 and 4332 DF,  p-value: < 2.2e-16

``` r
broom::tidy(my_model)
```

    ## # A tibble: 10 × 5
    ##    term              estimate std.error statistic   p.value
    ##    <chr>                <dbl>     <dbl>     <dbl>     <dbl>
    ##  1 (Intercept)       -5664.      98.2      -57.7  0        
    ##  2 blength              75.1      2.02      37.2  2.57e-263
    ##  3 gaweeks              11.8      1.46       8.11 6.67e- 16
    ##  4 bhead               129.       3.41      37.9  2.54e-271
    ##  5 delwt                 1.81     0.213      8.54 1.85e- 17
    ##  6 mraceBlack         -149.       9.23     -16.1  9.59e- 57
    ##  7 mraceAsian          -83.3     42.4       -1.96 4.96e-  2
    ##  8 mracePuerto Rican  -120.      18.7       -6.39 1.82e- 10
    ##  9 smoken               -4.91     0.587     -8.38 7.21e- 17
    ## 10 wtgain                2.39     0.423      5.64 1.77e-  8

**Description of modeling process:**

My proposed model is based on a hypothesized structure informed by
biological and medical knowledge about factors affecting birthweight:

**Biological/Physical Development Factors:** - `blength` (baby’s
length): Longer babies tend to weigh more - `bhead` (baby’s head
circumference): Larger head circumference indicates more fetal
development - `gaweeks` (gestational age): Longer gestation allows for
more growth

**Maternal Health Factors:** - `delwt` (mother’s delivery weight):
Maternal nutrition and body composition affect fetal growth - `wtgain`
(weight gain during pregnancy): Adequate weight gain supports fetal
development

**Behavioral Risk Factors:** - `smoken` (cigarettes per day): Smoking
during pregnancy is known to reduce birthweight

**Demographic Factors:** - `mrace` (mother’s race): May capture
socioeconomic and genetic factors affecting birthweight

The model achieved an adjusted R² of 0.715, indicating that these
predictors explain approximately 71.5% of the variability in
birthweight. All predictors except Asian mother’s race showed strong
statistical significance (p \< 0.001).

### 0.3.4 Residual plot

``` r
# Add predictions and residuals
birthweight_clean <- birthweight_clean %>%
  add_predictions(my_model) %>%
  add_residuals(my_model)

# Create residual plot
residual_plot <- birthweight_clean %>%
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.3, color = "steelblue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title = "Residuals vs Fitted Values",
    x = "Fitted Values",
    y = "Residuals"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"))

residual_plot
```

![](p8105_hw6_xl3493_files/figure-gfm/residual_plot-1.png)<!-- -->

1.  **Clustering Pattern**: The residuals show a distinct clustering
    pattern with higher density at certain fitted values, particularly
    around 3,000-3,500 grams, which corresponds to typical birthweights.
    This clustering is expected given the natural distribution of
    birthweights.

2.  **Heteroscedasticity**: There appears to be relatively constant
    variance across fitted values, though there may be slightly less
    spread at the extreme ends (very low and very high fitted values)
    due to fewer observations in these ranges.

3.  **Mean Zero**: The residuals are generally centered around zero with
    no obvious systematic pattern, suggesting the linearity assumption
    is reasonably met.

4.  **Outliers**: There are some notable outliers, particularly:

    - Several points with large negative residuals (observed birthweight
      much lower than predicted), with the most extreme around -1,100
      grams
    - Some points with large positive residuals (observed birthweight
      higher than predicted), with the most extreme around +2,300 grams
    - These outliers may represent cases with unusual medical conditions
      or measurement errors

    Despite the presence of outliers, the residual plot suggests that
    the linear model assumptions are reasonably satisfied.

### 0.3.5 Model comparisons

``` r
# Model 1: Length at birth and gestational age (main effects only)
model_1 <- lm(bwt ~ blength + gaweeks, data = birthweight_clean)

# Model 2: Head circumference, length, sex, and all interactions
model_2 <- lm(bwt ~ bhead * blength * babysex, data = birthweight_clean)

# View summaries
summary(model_1)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ blength + gaweeks, data = birthweight_clean)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -1709.6  -215.4   -11.4   208.2  4188.8 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) -4347.667     97.958  -44.38   <2e-16 ***
    ## blength       128.556      1.990   64.60   <2e-16 ***
    ## gaweeks        27.047      1.718   15.74   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 333.2 on 4339 degrees of freedom
    ## Multiple R-squared:  0.5769, Adjusted R-squared:  0.5767 
    ## F-statistic:  2958 on 2 and 4339 DF,  p-value: < 2.2e-16

``` r
summary(model_2)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ bhead * blength * babysex, data = birthweight_clean)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1132.99  -190.42   -10.33   178.63  2617.96 
    ## 
    ## Coefficients:
    ##                               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)                 -7176.8170  1264.8397  -5.674 1.49e-08 ***
    ## bhead                         181.7956    38.0542   4.777 1.84e-06 ***
    ## blength                       102.1269    26.2118   3.896 9.92e-05 ***
    ## babysexFemale                6374.8684  1677.7669   3.800 0.000147 ***
    ## bhead:blength                  -0.5536     0.7802  -0.710 0.478012    
    ## bhead:babysexFemale          -198.3932    51.0917  -3.883 0.000105 ***
    ## blength:babysexFemale        -123.7729    35.1185  -3.524 0.000429 ***
    ## bhead:blength:babysexFemale     3.8781     1.0566   3.670 0.000245 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 287.7 on 4334 degrees of freedom
    ## Multiple R-squared:  0.6849, Adjusted R-squared:  0.6844 
    ## F-statistic:  1346 on 7 and 4334 DF,  p-value: < 2.2e-16

### 0.3.6 Cross-validation

``` r
# Set up cross-validation
cv_df <- crossv_mc(birthweight_clean, n = 100)

# Fit models to each training set and calculate RMSE on test sets
cv_results <- cv_df %>%
  mutate(
    my_model = map(train, ~lm(
      bwt ~ blength + gaweeks + bhead + delwt + mrace + smoken + wtgain,
      data = .x
    )),
    model_1 = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    model_2 = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x))
  ) %>%
  mutate(
    rmse_my_model = map2_dbl(my_model, test, ~rmse(.x, .y)),
    rmse_model_1 = map2_dbl(model_1, test, ~rmse(.x, .y)),
    rmse_model_2 = map2_dbl(model_2, test, ~rmse(.x, .y))
  )

# View results
head(cv_results)
```

    ## # A tibble: 6 × 9
    ##   train                   test                  .id   my_model model_1 model_2
    ##   <list>                  <list>                <chr> <list>   <list>  <list> 
    ## 1 <resample [3,473 x 22]> <resample [869 x 22]> 001   <lm>     <lm>    <lm>   
    ## 2 <resample [3,473 x 22]> <resample [869 x 22]> 002   <lm>     <lm>    <lm>   
    ## 3 <resample [3,473 x 22]> <resample [869 x 22]> 003   <lm>     <lm>    <lm>   
    ## 4 <resample [3,473 x 22]> <resample [869 x 22]> 004   <lm>     <lm>    <lm>   
    ## 5 <resample [3,473 x 22]> <resample [869 x 22]> 005   <lm>     <lm>    <lm>   
    ## 6 <resample [3,473 x 22]> <resample [869 x 22]> 006   <lm>     <lm>    <lm>   
    ## # ℹ 3 more variables: rmse_my_model <dbl>, rmse_model_1 <dbl>,
    ## #   rmse_model_2 <dbl>

### 0.3.7 Comparison plot

``` r
# Prepare data for plotting
cv_plot_data <- cv_results %>%
  select(starts_with("rmse")) %>%
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>%
  mutate(
    model = factor(
      model,
      levels = c("my_model", "model_1", "model_2"),
      labels = c(
        "My Model",
        "Main Effects Only",
        "Interactions Model"
      )
    )
  )

# Create violin plot
cv_plot <- cv_plot_data %>%
  ggplot(aes(x = model, y = rmse, fill = model)) +
  geom_violin(alpha = 0.7) +
  geom_boxplot(width = 0.1, fill = "white", alpha = 0.5) +
  labs(
    title = "Cross-Validated Prediction Error Comparison",
    subtitle = "Based on 100-fold Monte Carlo cross-validation",
    x = "Model",
    y = "Root Mean Squared Error (RMSE)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "none"
  )

cv_plot
```

![](p8105_hw6_xl3493_files/figure-gfm/cv_plot-1.png)<!-- -->

``` r
# Calculate summary statistics
cv_summary <- cv_plot_data %>%
  group_by(model) %>%
  summarize(
    mean_rmse = mean(rmse),
    median_rmse = median(rmse),
    sd_rmse = sd(rmse)
  )

cv_summary
```

    ## # A tibble: 3 × 4
    ##   model              mean_rmse median_rmse sd_rmse
    ##   <fct>                  <dbl>       <dbl>   <dbl>
    ## 1 My Model                274.        274.    8.87
    ## 2 Main Effects Only       334.        330.   15.1 
    ## 3 Interactions Model      289.        291.   10.5

**Comparison and conclusions:**

Based on 100-fold Monte Carlo cross-validation, we compared three models
for predicting birthweight:

**Cross-Validation Results (RMSE):** - **My Model** (blength + gaweeks +
bhead + delwt + mrace + smoken + wtgain): Mean RMSE = 273.9, Median RMSE
= 274.6 - **Model 1** (blength + gaweeks only): Mean RMSE = 333.4,
Median RMSE = 330.2 - **Model 2** (bhead × blength × babysex
interactions): Mean RMSE = 289.0, Median RMSE = 289.3

------------------------------------------------------------------------

## 0.4 Session Info

``` r
sessionInfo()
```

    ## R version 4.3.3 (2024-02-29)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 24.04.1 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.12.0 
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.12.0
    ## 
    ## locale:
    ##  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
    ##  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
    ##  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
    ## [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
    ## 
    ## time zone: America/New_York
    ## tzcode source: system (glibc)
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ##  [1] p8105.datasets_0.0.1 modelr_0.1.11        broom_1.0.10        
    ##  [4] lubridate_1.9.4      forcats_1.0.1        stringr_1.5.2       
    ##  [7] dplyr_1.1.4          purrr_1.1.0          readr_2.1.5         
    ## [10] tidyr_1.3.1          tibble_3.3.0         ggplot2_4.0.0       
    ## [13] tidyverse_2.0.0     
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] bit_4.6.0          gtable_0.3.6       crayon_1.5.3       compiler_4.3.3    
    ##  [5] tidyselect_1.2.1   parallel_4.3.3     scales_1.4.0       yaml_2.3.10       
    ##  [9] fastmap_1.2.0      R6_2.6.1           labeling_0.4.3     generics_0.1.4    
    ## [13] curl_7.0.0         knitr_1.50         backports_1.5.0    pillar_1.11.1     
    ## [17] RColorBrewer_1.1-3 tzdb_0.5.0         rlang_1.1.6        utf8_1.2.6        
    ## [21] stringi_1.8.7      xfun_0.53          S7_0.2.0           bit64_4.6.0-1     
    ## [25] timechange_0.3.0   cli_3.6.5          withr_3.0.2        magrittr_2.0.4    
    ## [29] digest_0.6.37      grid_4.3.3         vroom_1.6.6        hms_1.1.4         
    ## [33] lifecycle_1.0.4    vctrs_0.6.5        evaluate_1.0.5     glue_1.8.0        
    ## [37] farver_2.1.2       rmarkdown_2.30     tools_4.3.3        pkgconfig_2.0.3   
    ## [41] htmltools_0.5.8.1
